import { useQuery, useMutation } from '@tanstack/react-query';

const API_BASE_URL = (typeof import.meta !== 'undefined' && import.meta.env?.VITE_API_BASE_URL) || 'http://localhost:8000';

// Mock data for development
const mockAttractions = [
  {
    id: '1',
    name: 'Nainital',
    description: 'A beautiful hill station famous for its pristine lake surrounded by mountains.',
    category: 'Nature',
    latitude: 29.3803,
    longitude: 79.4636,
    image: 'https://images.unsplash.com/photo-1610715936287-6c2ad208cdbf?w=800',
    rating: 4.5,
    bestTime: 'March to June',
    activities: ['Boating', 'Trekking', 'Photography'],
  },
  {
    id: '2',
    name: 'Rishikesh',
    description: 'The Yoga Capital of the World, known for spiritual experiences and adventure sports.',
    category: 'Spiritual',
    latitude: 30.0869,
    longitude: 78.2676,
    image: 'https://images.unsplash.com/photo-1678788166239-b28733f56956?w=800',
    rating: 4.8,
    bestTime: 'September to November',
    activities: ['Yoga', 'Rafting', 'Bungee Jumping'],
  },
  {
    id: '3',
    name: 'Jim Corbett National Park',
    description: 'India\'s oldest national park, home to Bengal tigers and diverse wildlife.',
    category: 'Wildlife',
    latitude: 29.5312,
    longitude: 78.7764,
    image: 'https://images.unsplash.com/photo-1611409518513-f062779abeeb?w=800',
    rating: 4.6,
    bestTime: 'November to February',
    activities: ['Safari', 'Bird Watching', 'Nature Walks'],
  },
  {
    id: '4',
    name: 'Valley of Flowers',
    description: 'A UNESCO World Heritage Site with endemic alpine flowers and stunning landscapes.',
    category: 'Nature',
    latitude: 30.7268,
    longitude: 79.5967,
    image: 'https://images.unsplash.com/photo-1530488283937-97dd1667472f?w=800',
    rating: 4.9,
    bestTime: 'July to September',
    activities: ['Trekking', 'Photography', 'Camping'],
  },
  {
    id: '5',
    name: 'Auli',
    description: 'Premier ski destination with panoramic views of Himalayan peaks.',
    category: 'Adventure',
    latitude: 30.5358,
    longitude: 79.5967,
    image: 'https://images.unsplash.com/photo-1641584495098-49cfceabd8e8?w=800',
    rating: 4.7,
    bestTime: 'December to March',
    activities: ['Skiing', 'Cable Car', 'Trekking'],
  },
  {
    id: '6',
    name: 'Mussoorie',
    description: 'Queen of Hills with colonial charm and breathtaking mountain views.',
    category: 'Nature',
    latitude: 30.4598,
    longitude: 78.0644,
    image: 'https://images.unsplash.com/photo-1717051041791-47c372799618?w=800',
    rating: 4.4,
    bestTime: 'April to June',
    activities: ['Cable Car', 'Shopping', 'Sightseeing'],
  },
];

const mockEvents = [
  // --- North India ---
  {
    id: '1',
    name: 'Kumbh Mela',
    date: '2025-01-15',
    location: 'Haridwar',
    description: 'The largest peaceful gathering of pilgrims on earth.',
    category: 'Religious',
    month: 1,
    state: 'Uttarakhand',
    regionType: 'Himalayan',
    significanceLevel: 'International',
  },
  {
    id: '2',
    name: 'International Yoga Festival',
    date: '2025-03-01',
    location: 'Rishikesh',
    description: 'Week-long celebration of yoga with renowned teachers.',
    category: 'Cultural',
    month: 3,
    state: 'Uttarakhand',
    regionType: 'Himalayan',
    significanceLevel: 'International',
  },
  {
    id: '3',
    name: 'Nanda Devi Raj Jat',
    date: '2025-08-15',
    location: 'Chamoli',
    description: 'Traditional pilgrimage to honor Goddess Nanda Devi.',
    category: 'Religious',
    month: 8,
    state: 'Uttarakhand',
    regionType: 'Himalayan',
    significanceLevel: 'State',
  },
  {
    id: '4',
    name: 'Uttarakhand Adventure Festival',
    date: '2025-10-10',
    location: 'Rishikesh',
    description: 'Celebrating adventure sports and outdoor activities.',
    category: 'Adventure',
    month: 10,
    state: 'Uttarakhand',
    regionType: 'Himalayan',
    significanceLevel: 'State',
  },
  {
    id: '5',
    name: 'Lohri',
    date: '2025-01-13',
    location: 'Amritsar',
    description: 'Harvest festival celebrated with bonfires, singing, and dancing.',
    category: 'Cultural',
    month: 1,
    state: 'Punjab',
    regionType: 'Urban',
    significanceLevel: 'State',
  },
  {
    id: '6',
    name: 'Holla Mohalla',
    date: '2025-03-15',
    location: 'Anandpur Sahib',
    description: 'Martial arts parade and mock battles by Nihang Sikhs.',
    category: 'Religious',
    month: 3,
    state: 'Punjab',
    regionType: 'Rural',
    significanceLevel: 'National',
  },
  {
    id: '7',
    name: 'Surajkund Crafts Mela',
    date: '2025-02-01',
    location: 'Faridabad',
    description: 'Largest crafts fair showcasing Indian handlooms and handicrafts.',
    category: 'Cultural',
    month: 2,
    state: 'Haryana',
    regionType: 'Urban',
    significanceLevel: 'National',
  },
  {
    id: '8',
    name: 'Kullu Dussehra',
    date: '2025-10-12',
    location: 'Kullu',
    description: 'Week-long festival celebrating the victory of Lord Raghunath.',
    category: 'Religious',
    month: 10,
    state: 'Himachal Pradesh',
    regionType: 'Himalayan',
    significanceLevel: 'National',
  },
  {
    id: '9',
    name: 'Losar',
    date: '2025-02-28',
    location: 'Spiti Valley',
    description: 'Tibetan New Year celebrated with masked dances and rituals.',
    category: 'Cultural',
    month: 2,
    state: 'Himachal Pradesh',
    regionType: 'Himalayan',
    significanceLevel: 'State',
  },
  {
    id: '10',
    name: 'Taj Mahotsav',
    date: '2025-02-18',
    location: 'Agra',
    description: 'Cultural festival displaying Art, Craft, and Culture of India.',
    category: 'Cultural',
    month: 2,
    state: 'Uttar Pradesh',
    regionType: 'Urban',
    significanceLevel: 'National',
  },
  {
    id: '11',
    name: 'Lathmar Holi',
    date: '2025-03-10',
    location: 'Barsana',
    description: 'Unique Holi celebration where women beat men with sticks playfully.',
    category: 'Cultural',
    month: 3,
    state: 'Uttar Pradesh',
    regionType: 'Rural',
    significanceLevel: 'International',
  },
  {
    id: '12',
    name: 'Dev Deepawali',
    date: '2025-11-26',
    location: 'Varanasi',
    description: 'Festival of Lights of the Gods on the ghats of the Ganges.',
    category: 'Religious',
    month: 11,
    state: 'Uttar Pradesh',
    regionType: 'Urban',
    significanceLevel: 'International',
  },

  // --- West India ---
  {
    id: '13',
    name: 'Pushkar Camel Fair',
    date: '2025-11-20',
    location: 'Pushkar',
    description: 'One of India\'s largest camel, horse and cattle fairs.',
    category: 'Cultural',
    month: 11,
    state: 'Rajasthan',
    regionType: 'Desert',
    significanceLevel: 'International',
  },
  {
    id: '14',
    name: 'Desert Festival',
    date: '2025-02-07',
    location: 'Jaisalmer',
    description: 'Showcasing the vibrant culture of the Thar Desert.',
    category: 'Cultural',
    month: 2,
    state: 'Rajasthan',
    regionType: 'Desert',
    significanceLevel: 'National',
  },
  {
    id: '15',
    name: 'Gangaur',
    date: '2025-04-11',
    location: 'Jaipur',
    description: 'Festival honoring Goddess Gauri, celebrated by women.',
    category: 'Religious',
    month: 4,
    state: 'Rajasthan',
    regionType: 'Urban',
    significanceLevel: 'State',
  },
  {
    id: '16',
    name: 'Rann Utsav',
    date: '2025-11-01',
    location: 'Kutch',
    description: 'Celebration of life and culture in the White Desert.',
    category: 'Cultural',
    month: 11,
    state: 'Gujarat',
    regionType: 'Desert',
    significanceLevel: 'National',
  },
  {
    id: '17',
    name: 'Navratri',
    date: '2025-10-03',
    location: 'Ahmedabad',
    description: 'Nine nights of dance and worship of Goddess Durga.',
    category: 'Religious',
    month: 10,
    state: 'Gujarat',
    regionType: 'Urban',
    significanceLevel: 'International',
  },
  {
    id: '18',
    name: 'International Kite Festival',
    date: '2025-01-14',
    location: 'Ahmedabad',
    description: 'Uttrayan celebration with kites filling the sky.',
    category: 'Adventure',
    month: 1,
    state: 'Gujarat',
    regionType: 'Urban',
    significanceLevel: 'International',
  },
  {
    id: '19',
    name: 'Ganesh Chaturthi',
    date: '2025-08-27',
    location: 'Mumbai',
    description: 'Grand celebration of Lord Ganesha\'s birth.',
    category: 'Religious',
    month: 8,
    state: 'Maharashtra',
    regionType: 'Urban',
    significanceLevel: 'International',
  },
  {
    id: '20',
    name: 'Ellora Ajanta Festival',
    date: '2025-01-10',
    location: 'Aurangabad',
    description: 'Focuses on the classical dance and music of India.',
    category: 'Cultural',
    month: 1,
    state: 'Maharashtra',
    regionType: 'Rural',
    significanceLevel: 'National',
  },
  {
    id: '21',
    name: 'Sunburn Festival',
    date: '2025-12-28',
    location: 'Vagator',
    description: 'Asia\'s largest electronic dance music festival.',
    category: 'Music',
    month: 12,
    state: 'Goa',
    regionType: 'Coastal',
    significanceLevel: 'International',
  },
  {
    id: '22',
    name: 'Goa Carnival',
    date: '2025-02-14',
    location: 'Panaji',
    description: 'Pre-Lenten carnival with parades, music, and masks.',
    category: 'Cultural',
    month: 2,
    state: 'Goa',
    regionType: 'Coastal',
    significanceLevel: 'National',
  },

  // --- East India ---
  {
    id: '23',
    name: 'Durga Puja',
    date: '2025-10-08',
    location: 'Kolkata',
    description: 'Grand worship of Goddess Durga, an artistic extravaganza.',
    category: 'Religious',
    month: 10,
    state: 'West Bengal',
    regionType: 'Urban',
    significanceLevel: 'International',
  },
  {
    id: '24',
    name: 'Poush Mela',
    date: '2025-12-23',
    location: 'Santiniketan',
    description: 'Folk music, food, and culture fair in Tagore\'s town.',
    category: 'Cultural',
    month: 12,
    state: 'West Bengal',
    regionType: 'Rural',
    significanceLevel: 'State',
  },
  {
    id: '25',
    name: 'Ratha Yatra',
    date: '2025-06-27',
    location: 'Puri',
    description: 'Chariot festival of Lord Jagannath.',
    category: 'Religious',
    month: 6,
    state: 'Odisha',
    regionType: 'Coastal',
    significanceLevel: 'International',
  },
  {
    id: '26',
    name: 'Konark Dance Festival',
    date: '2025-12-01',
    location: 'Konark',
    description: 'Classical dance festival against the backdrop of the Sun Temple.',
    category: 'Cultural',
    month: 12,
    state: 'Odisha',
    regionType: 'Coastal',
    significanceLevel: 'National',
  },
  {
    id: '27',
    name: 'Chhath Puja',
    date: '2025-10-28',
    location: 'Patna',
    description: 'Ancient festival dedicated to the Sun God.',
    category: 'Religious',
    month: 10,
    state: 'Bihar',
    regionType: 'Rural',
    significanceLevel: 'National',
  },
  {
    id: '28',
    name: 'Sonepur Mela',
    date: '2025-11-25',
    location: 'Sonepur',
    description: 'One of Asia\'s largest cattle fairs.',
    category: 'Cultural',
    month: 11,
    state: 'Bihar',
    regionType: 'Rural',
    significanceLevel: 'National',
  },
  {
    id: '29',
    name: 'Sarhul',
    date: '2025-04-06',
    location: 'Ranchi',
    description: 'Tribal festival celebrating the Sal tree and nature.',
    category: 'Cultural',
    month: 4,
    state: 'Jharkhand',
    regionType: 'Tribal',
    significanceLevel: 'State',
  },

  // --- North East India ---
  {
    id: '30',
    name: 'Hornbill Festival',
    date: '2025-12-01',
    location: 'Kisama',
    description: 'Festival of Festivals showcasing the rich culture of Nagaland.',
    category: 'Cultural',
    month: 12,
    state: 'Nagaland',
    regionType: 'Tribal',
    significanceLevel: 'International',
  },
  {
    id: '31',
    name: 'Bihu',
    date: '2025-04-14',
    location: 'Guwahati',
    description: 'Assamese New Year celebrated with fierce dance and music.',
    category: 'Cultural',
    month: 4,
    state: 'Assam',
    regionType: 'Rural',
    significanceLevel: 'State',
  },
  {
    id: '32',
    name: 'Ambubachi Mela',
    date: '2025-06-22',
    location: 'Guwahati',
    description: 'Tantric fertility festival at Kamakhya Temple.',
    category: 'Religious',
    month: 6,
    state: 'Assam',
    regionType: 'Urban',
    significanceLevel: 'National',
  },
  {
    id: '33',
    name: 'Ziro Festival of Music',
    date: '2025-09-25',
    location: 'Ziro Valley',
    description: 'Outdoor independent music festival in the Himalayas.',
    category: 'Music',
    month: 9,
    state: 'Arunachal Pradesh',
    regionType: 'Himalayan',
    significanceLevel: 'National',
  },
  {
    id: '34',
    name: 'Losar',
    date: '2025-02-28',
    location: 'Tawang',
    description: 'New Year celebration of the Monpa tribe.',
    category: 'Cultural',
    month: 2,
    state: 'Arunachal Pradesh',
    regionType: 'Himalayan',
    significanceLevel: 'State',
  },
  {
    id: '35',
    name: 'Wangala Festival',
    date: '2025-11-14',
    location: 'Asanang',
    description: 'Post-harvest festival of the Garo tribe, the 100 Drums Festival.',
    category: 'Cultural',
    month: 11,
    state: 'Meghalaya',
    regionType: 'Tribal',
    significanceLevel: 'State',
  },
  {
    id: '36',
    name: 'Chapchar Kut',
    date: '2025-03-07',
    location: 'Aizawl',
    description: 'Spring festival of Mizoram celebrated with Cheraw (bamboo dance).',
    category: 'Cultural',
    month: 3,
    state: 'Mizoram',
    regionType: 'Tribal',
    significanceLevel: 'State',
  },
  {
    id: '37',
    name: 'Sangai Festival',
    date: '2025-11-21',
    location: 'Imphal',
    description: 'Showcasing the rich culture and heritage of Manipur.',
    category: 'Cultural',
    month: 11,
    state: 'Manipur',
    regionType: 'Urban',
    significanceLevel: 'State',
  },
  {
    id: '38',
    name: 'Kharchi Puja',
    date: '2025-07-14',
    location: 'Agartala',
    description: 'Worship of fourteen gods, a major festival of Tripura.',
    category: 'Religious',
    month: 7,
    state: 'Tripura',
    regionType: 'Urban',
    significanceLevel: 'State',
  },
  {
    id: '39',
    name: 'Saga Dawa',
    date: '2025-06-11',
    location: 'Gangtok',
    description: 'Celebrates the birth, enlightenment, and death of Buddha.',
    category: 'Religious',
    month: 6,
    state: 'Sikkim',
    regionType: 'Himalayan',
    significanceLevel: 'State',
  },

  // --- Central India ---
  {
    id: '40',
    name: 'Khajuraho Dance Festival',
    date: '2025-02-20',
    location: 'Khajuraho',
    description: 'Classical dance performances against magnificent temples.',
    category: 'Cultural',
    month: 2,
    state: 'Madhya Pradesh',
    regionType: 'Rural',
    significanceLevel: 'International',
  },
  {
    id: '41',
    name: 'Bhagoria Festival',
    date: '2025-03-08',
    location: 'Jhabua',
    description: 'Tribal festival of the Bhils and Bhilalas involving matchmaking.',
    category: 'Cultural',
    month: 3,
    state: 'Madhya Pradesh',
    regionType: 'Tribal',
    significanceLevel: 'State',
  },
  {
    id: '42',
    name: 'Bastar Dussehra',
    date: '2025-10-12',
    location: 'Jagdalpur',
    description: 'Unique tribal Dussehra spanning 75 days.',
    category: 'Cultural',
    month: 10,
    state: 'Chhattisgarh',
    regionType: 'Tribal',
    significanceLevel: 'National',
  },

  // --- South India ---
  {
    id: '43',
    name: 'Onam',
    date: '2025-09-06',
    location: 'Kerala',
    description: 'Harvest festival of Kerala celebrated with boat races and sadhya.',
    category: 'Cultural',
    month: 9,
    state: 'Kerala',
    regionType: 'Coastal',
    significanceLevel: 'International',
  },
  {
    id: '44',
    name: 'Thrissur Pooram',
    date: '2025-05-08',
    location: 'Thrissur',
    description: 'The most spectacular temple festival of Kerala with elephants.',
    category: 'Religious',
    month: 5,
    state: 'Kerala',
    regionType: 'Urban',
    significanceLevel: 'National',
  },
  {
    id: '45',
    name: 'Pongal',
    date: '2025-01-14',
    location: 'Madurai',
    description: 'Harvest festival giving thanks to nature and the Sun.',
    category: 'Cultural',
    month: 1,
    state: 'Tamil Nadu',
    regionType: 'Rural',
    significanceLevel: 'National',
  },
  {
    id: '46',
    name: 'Meenakshi Tirukalyanam',
    date: '2025-04-20',
    location: 'Madurai',
    description: 'Celestial wedding of Goddess Meenakshi and Lord Sundareswarar.',
    category: 'Religious',
    month: 4,
    state: 'Tamil Nadu',
    regionType: 'Urban',
    significanceLevel: 'National',
  },
  {
    id: '47',
    name: 'Hampi Utsav',
    date: '2025-11-03',
    location: 'Hampi',
    description: 'Cultural extravaganza amidst the ruins of Vijayanagara Empire.',
    category: 'Cultural',
    month: 11,
    state: 'Karnataka',
    regionType: 'Rural',
    significanceLevel: 'National',
  },
  {
    id: '48',
    name: 'Mysore Dasara',
    date: '2025-10-12',
    location: 'Mysore',
    description: 'Grand royal procession and lighting of the Mysore Palace.',
    category: 'Cultural',
    month: 10,
    state: 'Karnataka',
    regionType: 'Urban',
    significanceLevel: 'International',
  },
  {
    id: '49',
    name: 'Bonalu',
    date: '2025-07-20',
    location: 'Hyderabad',
    description: 'Festival dedicated to Goddess Mahakali.',
    category: 'Religious',
    month: 7,
    state: 'Telangana',
    regionType: 'Urban',
    significanceLevel: 'State',
  },
  {
    id: '50',
    name: 'Bathukamma',
    date: '2025-10-02',
    location: 'Telangana',
    description: 'Flower festival celebrated by women.',
    category: 'Cultural',
    month: 10,
    state: 'Telangana',
    regionType: 'Urban',
    significanceLevel: 'State',
  },
  {
    id: '51',
    name: 'Ugadi',
    date: '2025-03-30',
    location: 'Andhra Pradesh',
    description: 'Telugu New Year.',
    category: 'Cultural',
    month: 3,
    state: 'Andhra Pradesh',
    regionType: 'Urban',
    significanceLevel: 'State',
  },

  // --- Union Territories ---
  {
    id: '52',
    name: 'Hemis Festival',
    date: '2025-07-06',
    location: 'Leh',
    description: 'Colorful festival at Hemis Monastery dedicated to Guru Padmasambhava.',
    category: 'Cultural',
    month: 7,
    state: 'Ladakh',
    regionType: 'Himalayan',
    significanceLevel: 'International',
  },
  {
    id: '53',
    name: 'Tulip Festival',
    date: '2025-04-05',
    location: 'Srinagar',
    description: 'Celebration of blooming tulips in Asia\'s largest tulip garden.',
    category: 'Nature',
    month: 4,
    state: 'Jammu & Kashmir',
    regionType: 'Himalayan',
    significanceLevel: 'National',
  },
  {
    id: '54',
    name: 'Shikara Festival',
    date: '2025-08-10',
    location: 'Dal Lake',
    description: 'Celebrating the traditional wooden boats of Kashmir.',
    category: 'Cultural',
    month: 8,
    state: 'Jammu & Kashmir',
    regionType: 'Himalayan',
    significanceLevel: 'State',
  },
  {
    id: '55',
    name: 'Island Tourism Festival',
    date: '2025-01-05',
    location: 'Port Blair',
    description: 'Showcasing the culture and beauty of the islands.',
    category: 'Cultural',
    month: 1,
    state: 'Andaman & Nicobar Islands',
    regionType: 'Coastal',
    significanceLevel: 'National',
  },
  {
    id: '56',
    name: 'Rose Festival',
    date: '2025-02-21',
    location: 'Chandigarh',
    description: 'Exhibition of thousands of rose varieties.',
    category: 'Nature',
    month: 2,
    state: 'Chandigarh',
    regionType: 'Urban',
    significanceLevel: 'State',
  },
  {
    id: '57',
    name: 'Pondicherry Heritage Festival',
    date: '2025-02-05',
    location: 'Pondicherry',
    description: 'Celebrating the colonial and spiritual heritage.',
    category: 'Cultural',
    month: 2,
    state: 'Puducherry',
    regionType: 'Coastal',
    significanceLevel: 'State',
  },
  {
    id: '58',
    name: 'Qutub Festival',
    date: '2025-11-15',
    location: 'New Delhi',
    description: 'Music and dance festival at Qutub Minar complex.',
    category: 'Music',
    month: 11,
    state: 'Delhi',
    regionType: 'Urban',
    significanceLevel: 'National',
  },
  {
    id: '59',
    name: 'Trade Fair (IITF)',
    date: '2025-11-14',
    location: 'New Delhi',
    description: 'International trade fair at Pragati Maidan.',
    category: 'Cultural',
    month: 11,
    state: 'Delhi',
    regionType: 'Urban',
    significanceLevel: 'International',
  },
  {
    id: '60',
    name: 'Eid-ul-Fitr',
    date: '2025-03-31',
    location: 'Delhi',
    description: 'Celebration marking the end of Ramadan.',
    category: 'Religious',
    month: 3,
    state: 'Delhi',
    regionType: 'Urban',
    significanceLevel: 'International',
  },
  {
    id: '61',
    name: 'Diwali',
    date: '2025-10-20',
    location: 'Delhi',
    description: 'Festival of lights celebrated across the nation.',
    category: 'Religious',
    month: 10,
    state: 'Delhi',
    regionType: 'Urban',
    significanceLevel: 'International',
  },
  {
    id: '62',
    name: 'Christmas',
    date: '2025-12-25',
    location: 'Goa',
    description: 'Celebration of the birth of Jesus Christ, particularly grand in Goa.',
    category: 'Religious',
    month: 12,
    state: 'Goa',
    regionType: 'Coastal',
    significanceLevel: 'International',
  },
  {
    id: '63',
    name: 'Nagoa Beach Festival',
    date: '2025-01-05',
    location: 'Diu',
    description: 'Cultural events and adventure sports by the beach.',
    category: 'Adventure',
    month: 1,
    state: 'Dadra & Nagar Haveli and Daman & Diu',
    regionType: 'Coastal',
    significanceLevel: 'State',
  },
];

const mockRoutes = [
  {
    id: '1',
    name: 'Spiritual Journey',
    places: ['Haridwar', 'Rishikesh', 'Devprayag'],
    duration: '3 days',
    distance: '120 km',
  },
  {
    id: '2',
    name: 'Wildlife & Nature',
    places: ['Jim Corbett', 'Nainital', 'Ranikhet'],
    duration: '5 days',
    distance: '250 km',
  },
  {
    id: '3',
    name: 'Adventure Trail',
    places: ['Rishikesh', 'Auli', 'Valley of Flowers'],
    duration: '7 days',
    distance: '400 km',
  },
];

// API Functions
async function fetchAttractions() {
  try {
    const response = await fetch(`${API_BASE_URL}/attractions`);
    if (!response.ok) throw new Error('Failed to fetch');
    return response.json();
  } catch (error) {
    console.log('Using mock data for attractions');
    return mockAttractions;
  }
}

async function fetchEvents() {
  try {
    const response = await fetch(`${API_BASE_URL}/events`);
    if (!response.ok) throw new Error('Failed to fetch');
    return response.json();
  } catch (error) {
    console.log('Using mock data for events');
    return mockEvents;
  }
}

async function fetchRoutes() {
  try {
    const response = await fetch(`${API_BASE_URL}/routes`);
    if (!response.ok) throw new Error('Failed to fetch');
    return response.json();
  } catch (error) {
    console.log('Using mock data for routes');
    return mockRoutes;
  }
}

async function sendChatMessage(message: string) {
  try {
    const response = await fetch(`${API_BASE_URL}/chat`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ query: message }),
    });
    if (!response.ok) throw new Error('Failed to send message');
    return response.json();
  } catch (error) {
    console.log('Using mock response for chat');
    // Mock AI response
    return {
      response: `I'd be happy to help you explore ${message.includes('Nainital') ? 'Nainital' : 'Uttarakhand'}! This beautiful destination offers stunning natural beauty, spiritual experiences, and adventure activities. Would you like me to suggest a detailed itinerary?`,
      sources: [
        { name: 'Uttarakhand Tourism Board', url: '#' },
        { name: 'Travel Guide 2025', url: '#' },
      ],
      suggestions: ['Plan 3-day itinerary', 'Best time to visit', 'Local cuisine'],
    };
  }
}

async function generateItinerary(data: any) {
  try {
    const response = await fetch(`${API_BASE_URL}/plan`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data),
    });
    if (!response.ok) throw new Error('Failed to generate itinerary');
    return response.json();
  } catch (error) {
    console.log('Using mock itinerary');
    return {
      days: [
        {
          day: 1,
          title: 'Arrival & Local Exploration',
          activities: [
            { time: '10:00 AM', activity: 'Check-in at hotel', location: data.destination },
            { time: '2:00 PM', activity: 'Local market visit', location: data.destination },
            { time: '6:00 PM', activity: 'Evening at lakeside', location: data.destination },
          ],
        },
        {
          day: 2,
          title: 'Adventure & Sightseeing',
          activities: [
            { time: '8:00 AM', activity: 'Sunrise trek', location: 'Nearby hills' },
            { time: '12:00 PM', activity: 'Local cuisine lunch', location: 'Popular restaurant' },
            { time: '4:00 PM', activity: 'Visit main attractions', location: data.destination },
          ],
        },
      ],
      totalCost: '₹15,000 - ₹25,000',
      tips: ['Book accommodation in advance', 'Carry warm clothing', 'Try local cuisine'],
    };
  }
}

// Custom Hooks
export function useAttractions() {
  return useQuery({
    queryKey: ['attractions'],
    queryFn: fetchAttractions,
  });
}

export function useEvents() {
  return useQuery({
    queryKey: ['events'],
    queryFn: fetchEvents,
  });
}

export function useRoutes() {
  return useQuery({
    queryKey: ['routes'],
    queryFn: fetchRoutes,
  });
}

export function useChatMessage() {
  return useMutation({
    mutationFn: sendChatMessage,
  });
}

export function useGenerateItinerary() {
  return useMutation({
    mutationFn: generateItinerary,
  });
}